name: S3 sync action

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4 # Actualizado a v4

      - name: Connect to AWS
        uses: aws-actions/configure-aws-credentials@v4 # Actualizado a v4
        with:
          role-session-name: awssyncsession
          role-to-assume: arn:aws:iam::130063747200:role/github-trust-role
          aws-region: us-east-1

      - name: Sync bucket
        run: aws s3 sync ./files/ s3://github-trust-coronel  --delete